IS2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home, name = 'home'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^auth/', include('autenticacion.urls')),
    url(r'^recursos/', include('recursos.urls')),
    url(r'^notificaciones/', include('notificaciones.urls')),
    url(r'^reservas/', include('reservas.urls')),
]

reservas/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
        url(r'^consultar$', views.listar_reservas.as_view(), name='ConsultaDeReservas'),
        url(r'^reservaDisponibilidad', views.reserva_disponibilidad,name='ReservaDisponibilidad'),
        url(r'^reporte$', views.reporte_reservas.as_view(), name='reporte_reservas'),
        url(r'^dashboardFH$', views.dashboardFranjaview.as_view(),name='DashboardFH'),
    ]

reservas/models.py
from django.db import models
from recursos.models import Recurso
from administracion.models import Usuario
import datetime

Horas_catedras=(
    (0,'07:30 AM'),
    (1,'08:15 AM'),
    (2,'09:00 AM'),
    (3,'09:45 AM'),
    (4,'10:30 AM'),
    (5,'11:15 PM'),
    (6,'12:00 PM'),
    (7,'12:45 PM'),
    (8,'13:15 PM'),
    (9,'14:00 PM'),
    (10,'14:45 PM'),
    (11,'15:30 PM'),
    (12,'16:15 PM'),
    (13,'17:00 PM'),
    (14,'17:45 PM'),
    (15,'18:30 PM'),
    (16,'19:15 PM'),
    (17,'20:00 PM'),
    (18,'20:45 PM'),
)

class Reserva(models.Model):
    '''Clase que representa a la Reserva dentro del sistema'''
    Tipo_Reserva = (
        ('0', 'Por disponibilidad'),
        ('1', 'Por recurso específico'),
    )
    Estado_Reserva=(
        ('0', 'En Espera'),                 # Recurso todavia no ha sido adjudicado
        ('1', 'Aprobado'),                  # Recurso ha sido adjudicado a esta reserva
        ('2', 'Rechazado'),                 # Recurso ha sido adjudicado a otra reserva
        ('3', 'Finalizado'),
        ('4', 'Cancelado')
    )
    fecha = models.DateField()
    hora_inicio = models.IntegerField(choices=Horas_catedras,null=False)
    hora_fin = models.IntegerField(choices=Horas_catedras,null=False)
    recurso = models.ForeignKey(Recurso, null=False)
    tipo = models.CharField(max_length=1, choices=Tipo_Reserva, null=False)
    estado = models.CharField(max_length=1, choices=Estado_Reserva, default='0')
    responsable = models.ForeignKey(Usuario)
    posicion = models.IntegerField(verbose_name='posicion en cola de espera', default=1)
    def __str__(self):
        return self.recurso.__str__() + ' para ' + self.responsable.__str__()

class MiReserva(Reserva):
    '''Clase proxy que representa las reservas desde el punto de vista del solicitante'''
    class Meta:
        proxy = True
        verbose_name = 'mi reserva'
        verbose_name_plural = 'mis reservas'

    def __str__(self):
        return self.recurso.__str__() + ' para fecha: ' + self.fecha.isoformat()

class ColaDePrioridades(models.Model):
    '''Cola de prioridades para reservas'''
    fecha=models.DateField()
    recurso=models.ForeignKey(Recurso)
    hora_catedra=models.IntegerField(choices=Horas_catedras)
    cola=models.CharField(max_length=255)           # cola va alvergar una cadena que representa un array de enteros
                                                    # donde los enteros son ids de reserva
class ControlReserva(models.Model):
    reserva = models.ForeignKey(Reserva)
    Estado_Reserva = (
        ('0', 'En espera'),  # Recurso todavia no ha sido entregado
        ('1', 'En ejecucion'),  # Recurso se entrego
        ('2', 'Finalizado'),  # Recurso se devolvio
    )
    estado = models.CharField(max_length=1, choices=Estado_Reserva, default='0')
    obs = models.CharField(max_length=300)

    def __str__(self):
        return str(self.reserva.id)

reservas/forms.py
from django import forms
from recursos.models import TipoRecurso, Recurso
from .models import Horas_catedras,Reserva
import  datetime
from administracion.models import Usuario

class ReservaDisponibilidadForm(forms.Form):
    '''Formulario utilizado para la creacion de Reservas Segun Disponibilidad'''
    tipo = forms.ModelChoiceField(queryset=TipoRecurso.objects.all())
    fecha = forms.DateField()
    inicio = forms.ChoiceField(Horas_catedras)
    fin = forms.ChoiceField(Horas_catedras)

    def clean(self):
        cleaned_data = super(ReservaDisponibilidadForm,self).clean()
        fecha = cleaned_data.get("fecha")
        inicio = cleaned_data.get("inicio")
        fin = cleaned_data.get("fin")

        if fecha < datetime.date.today():
            raise forms.ValidationError("Inserte una Fecha Valida")

        if fin <= inicio:
            raise forms.ValidationError("La hora de fin debe ser mayor a la de inicio")

class reporte_reserva_form(forms.Form):
    '''Clase que representa un formulario usado en la vista de reportes de reservas'''
    tipo = forms.ModelChoiceField(queryset=Recurso.objects.all(), required=False, initial=None, label='Recurso')
    estado = forms.ChoiceField(widget=forms.Select(),
                               choices=([('vacio', '------------'), ('0', 'En Espera'),('1', 'Aprobado'),('2', 'Rechazado'),('3', 'Finalizado'),('4', 'Cancelado')]), initial='vacio')
    responsable = forms.ModelChoiceField(queryset=Usuario.objects.filter(groups__name='Solicitante'),
                                         required=False, initial=None)
    fecha = forms.DateField(input_formats=['%d-%M-%Y'],required= False)

reservas/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, FormView, TemplateView
from .models import Reserva,Horas_catedras
from .forms import ReservaDisponibilidadForm,reporte_reserva_form
from datetime import timedelta,date
from recursos.models import Recurso
from django.urls import reverse,reverse_lazy
from django.views.generic.edit import FormMixin
from django.core.mail import send_mail
from notificaciones.models import notificacion
from .models import ControlReserva


class listar_reservas(ListView):
    '''Vista que se utiliza para listar las reservas'''
    model = Reserva
    template_name = 'reservas/ConsultaDeReservas.html'
    def get_queryset(self):
        return Reserva.objects.filter(responsable=self.request.user)

def reserva_disponibilidad(request):
    '''Vista utilizada para la creacion de las reservas segun disponibilidad de Recursos'''
    if request.method == "POST":
        form = ReservaDisponibilidadForm(request.POST)
        if form.is_valid():
            tipo = form.cleaned_data['tipo']
            fecha = form.cleaned_data['fecha']
            inicio = int(form.cleaned_data['inicio'])
            fin = int(form.cleaned_data['fin'])
            solicitante = request.user
            dias = 7  #rango maximo de dias en el que se puede realizar una reserva
            if(fecha - timedelta(days=dias) <= date.today() ):
                recursosReservas = Reserva.objects.all().exclude(estado__exact='3').values_list('recurso',flat=True).distinct()
                recursos = Recurso.objects.filter(tipo=tipo,disponible=True)
                recurso = None
                for rec in recursos:
                    disponible = True
                    if (rec.id in recursosReservas):
                        reservas = Reserva.objects.filter(recurso=rec,fecha__exact=fecha)
                        for reserva in reservas:
                            if inicio < reserva.hora_inicio and fin > reserva.hora_inicio:
                                disponible = False
                                break
                            elif inicio >= reserva.hora_inicio and inicio < reserva.hora_fin:
                                disponible = False
                                break
                        if(disponible == True):
                            recurso = rec
                            break
                    else:
                        recurso = rec
                        break
                if (recurso == None):
                    return render(request, 'reservas/reserva_disponibilidad.html',{'mensaje': 'No se encontro ningun recurso Disponible'})
                reserva = Reserva.objects.create(fecha=fecha,hora_inicio=inicio,hora_fin=fin,recurso=recurso,tipo=0,estado=1,responsable=solicitante)
                reserva.save()
                controlRes = ControlReserva.objects.create(estado = 0, reserva_id = reserva.id)
                controlRes.save()
                enviar_correo(solicitante,inicio ,fin ,fecha,recurso)

                return render(request, 'reservas/reserva_disponibilidad.html',{'mensaje': 'Su reserva fue creada correctamente'})
            else:
                return render(request, 'reservas/reserva_disponibilidad.html',{'mensaje': 'Solo se puede realizar reservas en un plazo de '+ str(dias) + ' dias'})
    else:
        form = ReservaDisponibilidadForm()
    return render(request, 'reservas/reserva_disponibilidad.html', {'form': form})

def enviar_correo(solicitante, inicio , fin ,fecha,recurso):
    '''Metodo utilizado para enviar el correo electronico al solicitante'''
    email = solicitante.email
    subject = notificacion.objects.get(titulo="Reserva Acreditada").titulo
    message = notificacion.objects.get(titulo="Reserva Acreditada").texto + \
              "\nSolicitante: " + solicitante.first_name + " " + solicitante.last_name + \
              "\nRecurso: " + recurso.__str__() + \
              "\nFecha: " + str(fecha) + \
              "\nHora Inicio :" + Horas_catedras[inicio][1] + \
                        "\nHora Fin: " + Horas_catedras[fin][1] + "\n"
    send_mail(subject,message,"teamsgr17@gmail.com",[email])

class dashboardFranjaview(TemplateView):

    template_name = "portalPublico/dashboardFranjaHoraria.html"

    def get_lista_horas(self):
        lista_horas = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]
        reservas=Reserva.objects.all().exclude(estado="4")
        for reserva in reservas:
            for i in range(reserva.hora_inicio, reserva.hora_fin + 1, 1):
                lista_horas[i]+=1
        return lista_horas
    def get_labels(self):
        labels= []
        for label in Horas_catedras:
            labels.append(label[1])
        return labels

    def get_context_data(self, **kwargs):
        context = super(dashboardFranjaview, self).get_context_data(**kwargs)
        context['data'] = self.get_lista_horas()
        context['labels'] = self.get_labels()
        return context



class FormListView(FormMixin,ListView):
    def get(self, request, *args, **kwargs):
        # From ProcessFormMixin
        form_class = self.get_form_class()
        self.form = self.get_form(form_class)
        try:
            tipo = self.form.data['tipo']
            responsable = self.form.data['responsable']
            estado = self.form.data['estado']
            fecha = self.form.data['fecha']
            fecha = fecha[6:10] + '-' + fecha[3:5] + '-' + fecha[0:2]
            if (estado == 'vacio'):
                self.object_list = self.get_queryset()
            else:
                self.object_list = self.get_queryset().filter(estado=estado)

            if (tipo != ''):
                self.object_list = self.object_list.filter(tipo=tipo)

            if (responsable != ''):
                self.object_list = self.object_list.filter(responsable=responsable)

            if (fecha != '' and fecha != '--'):
                self.object_list = self.object_list.filter(fecha=fecha)

        except:
            self.object_list = self.get_queryset()
        allow_empty = self.get_allow_empty()
        if not allow_empty and len(self.object_list) == 0:
            raise (u"Empty list and '%(class_name)s.allow_empty' is False.")

        context = self.get_context_data(object_list=self.object_list, form=self.form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

class reporte_reservas(FormListView):
    form_class = reporte_reserva_form
    model = Reserva
    template_name = 'reservas/reporte.html'
    success_url = reverse_lazy('reporte_reservas')

templates/reservas/ConsultaDeReservas.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block body %}
<div class="col-md-4 col-md-offset-4" style="margin-top: 4%">
    <div class="panel panel-default">
            <div class="panel-heading">Lista de Reservas</div>
        <div class="panel-body">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th><strong>Responsable</strong></th>
                    <th><strong>Recurso</strong></th>
                </tr>
                </thead>
            <tbody>
                {% for objeto in object_list %}
                        <td>{{ objeto.responsable}}</td>
                        <td>{{ objeto.recurso}}</td>
                    <tr/>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
 </div>
{% endblock %}

templates/reservas/reporte.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block body %}
<div class = "col-md-10  col-md-offset-1" style="margin-top: 2%; margin-bottom: 2%;">
    <form action="" method="POST" class="form-inline" >
        {% csrf_token %}
        {% bootstrap_form form%}
        {% buttons %}
            <input type="submit" class="btn btn-default "  value="Ir" />
        {% endbuttons %}
    </form>
</div>
<div class="col-md-10 col-md-offset-1" >
    <div class="panel panel-default">
            <div class="panel-heading">Reporte de Reservas</div>
        <div class="panel-body">
            <table class="table table-hover table-condensed">
                <thead>
                <tr>
                    <th><strong>Tipo</strong></th>
                    <th>Estado</th>
                    <th>Responsable</th>
                    <th>Fecha</th>
                </tr>
                </thead>
            <tbody>
                {% for objeto in object_list %}
                    <tr>
                        <td>{{ objeto.get_tipo_display}}</td>
                        <td>{{ objeto.get_estado_display}}</td>
                        <td> {{ objeto.responsable }} </td>
                        <td> {{ objeto.fecha }} </td>
                    </tr>
                {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
 </div>
{% endblock %}

templates/reservas/reserva_disponibilidad.html
{% extends 'home.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% block body %}
    <div class="col-md-4 col-md-offset-4" style="margin-top: 10%">
        <div class="panel panel-default"  >
            <div class="panel-heading">Reserva segun Disponibilidad</div>
            <div class="panel-body  ">
                <form action="" method="POST" >
                {% csrf_token %}
                {% if mensaje %}
                    {{ mensaje }}<br><br>
                    <input type="button" class="btn btn-default "  value="Volver"  onclick="location.href='{% url 'ReservaDisponibilidad' %}'"/>
                {% else %}
                    {% bootstrap_form form %}
                    {% buttons %}
                        <button type="submit" class="btn btn-default">Aceptar</button>
                        <input type="button" class="btn btn-default "  value="Cancelar"  onclick="location.href='{% url 'home' %}'"/>
                    {% endbuttons %}
                {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}